### ISSUE TITLE
Please remove unnecessary files

### ISSUE THREAD

**Issue by pcav** [ilayarajak/ToRadians#2]
.pyc etc.
They are generated automatically during installation.
Thanks.

**Comment by ilayarajak** [comment]
Yes. I have made the changes
Thanks.

**Comment by pcav** [comment]
Apparently not, e.g.: https://github.com/noiromo/S-411_Ice_Loader/tree/master/__pycache__

**Comment by ilayarajak** [comment]
Yes. I have made the changes
Thanks.

**Comment by pcav** [comment]
Thanks.
